# Copyright (c) 2026 Microsoft Corporation. All rights reserved.
# SPDX-License-Identifier: MIT

from __future__ import annotations

from pathlib import Path
from typing import Any

from runtime_a11y.matrix._model import Matrix
from runtime_a11y.matrix._provenance import ArtifactMetadata

ACCESSIBILITY_DISCLAIMER = (
    "> [!CAUTION]\n"
    "> **Disclaimer:** This agent is an assistive tool only. It does not "
    "provide legal, regulatory, accessibility conformance, or compliance "
    "advice and does not replace accessibility specialists, accessibility "
    "review boards, VPAT auditors, ACR signers, or EAA conformance "
    "assessors. The output consists of suggested actions and "
    "considerations to support a user's own internal accessibility review "
    "and decision-making. All accessibility assessments, framework "
    "selections, control mappings, evidence registers, tradeoff records, "
    "conformance summaries, and backlog items generated by this tool must "
    "be independently reviewed and validated by appropriate accessibility "
    "and compliance reviewers before use. Outputs from this tool do not "
    "constitute accessibility conformance approval, compliance "
    "certification, VPAT attestation, EAA conformance, or regulatory "
    "sign-off. This AI-assisted plan requires qualified human review "
    "before any external publication, customer disclosure, procurement "
    "response, or regulatory submission."
)
HUMAN_REVIEW_CHECKBOX = "- [ ] Reviewed and validated by a qualified human reviewer"


def render_markdown(
    matrix: Matrix,
    coverage: dict[str, Any],
    out_path: Path,
    repo_slug: str,
    metadata: ArtifactMetadata | None = None,
) -> None:
    """Render a markdown coverage summary for the matrix."""
    lines: list[str] = []
    lines.append("<!-- markdownlint-disable-file -->")
    lines.append("# Accessibility Coverage Matrix")
    lines.append("")
    lines.append(ACCESSIBILITY_DISCLAIMER)
    lines.append("")
    lines.append(HUMAN_REVIEW_CHECKBOX)
    lines.append("")
    lines.append(f"- Repository: {repo_slug}")
    if metadata is not None and metadata.quarantined:
        lines.append(
            "- Quarantined: derived from a run that ended in an operational "
            f"failure ({metadata.quarantineReason or 'reason not recorded'}). "
            "Not a basis for a conformance claim."
        )
    lines.append("")
    lines.append("## Coverage Summary")
    lines.append("")
    lines.append(
        f"- Overall coverage: {coverage.get('overall', {}).get('coverage', 0.0)}%"
    )
    lines.append("")
    lines.append("## Per-Framework Coverage")
    lines.append("")
    lines.append("| Framework | Coverage | Numerator | Denominator |")
    lines.append("|-----------|----------|-----------|-------------|")
    frameworks = coverage.get("frameworks", {}) or {}
    for framework_name, stats in sorted(frameworks.items()):
        lines.append(
            f"| {framework_name} | {stats.get('coverage', 0.0)}% | "
            f"{stats.get('numerator', 0)} | {stats.get('denominator', 0)} |"
        )
    lines.append("")
    lines.append("## Residual by Method")
    lines.append("")
    residual = coverage.get("residual", []) or []
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in residual:
        method = str(item.get("verifiedByMethod") or "unknown")
        grouped.setdefault(method, []).append(item)
    if grouped:
        for method_name in sorted(grouped):
            lines.append(f"### {method_name}")
            lines.append("")
            for item in grouped[method_name]:
                lines.append(
                    f"- {item['criterionId']} / {item['surfaceId']} / "
                    f"{item['state']} ({item['status']})"
                )
            lines.append("")
    else:
        lines.append("- None")
        lines.append("")
    lines.append("## Probe Run Summary")
    lines.append("")
    lines.append("- Runtime probe data is summarized here when available.")
    lines.append("")
    lines.append("## Next Actions")
    lines.append("")
    next_actions = coverage.get("nextActions", []) or []
    if next_actions:
        for action in next_actions:
            lines.append(
                f"- {action['criterionId']} / {action['surfaceId']} / "
                f"{action['state']} ({action['priority']})"
            )
    else:
        lines.append("- None")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
