#!/usr/bin/env python3
"""Generate CATALOG.md from the converted plugin's frontmatter."""
import re
import sys
from pathlib import Path

import yaml

root = Path(sys.argv[1] if len(sys.argv) > 1 else "plugins/hve-core")
out = Path(sys.argv[2] if len(sys.argv) > 2 else "CATALOG.md")


def fm_of(p: Path) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", p.read_text(encoding="utf-8"), re.S)
    return yaml.safe_load(m.group(1)) if m else {}


entry, background, hidden = [], [], []
for p in sorted(root.glob("skills/*/SKILL.md")):
    fm = fm_of(p)
    row = (fm.get("name", p.parent.name), str(fm.get("description", "")).strip().replace("|", "\\|"),
           str(fm.get("argument-hint", "")).replace("|", "\\|"))
    if fm.get("user-invocable") is False:
        hidden.append(row + (", ".join(fm.get("paths", [])) if fm.get("paths") else "by name",))
    elif fm.get("disable-model-invocation"):
        entry.append(row)
    else:
        background.append(row)
agents = [(fm_of(p).get("name", p.stem), str(fm_of(p).get("description", "")).strip().replace("|", "\\|"))
          for p in sorted(root.glob("agents/*.md"))]

L = ["# HVE Core for Claude Code — catalog", "",
     f"{len(entry)} entry-point commands, {len(background)} auto-loading skills, "
     f"{len(hidden)} path/by-name instruction skills, {len(agents)} subagents. Generated by `scripts/build_catalog.py`.", "",
     "## Entry points (you invoke these)", "", "| Command | Purpose | Arguments |", "|---|---|---|"]
L += [f"| `/hve-core:{n}` | {d} | `{a}` |" if a else f"| `/hve-core:{n}` | {d} | |" for n, d, a in entry]
L += ["", "## Skills Claude loads on its own (also callable by name)", "", "| Skill | Purpose |", "|---|---|"]
L += [f"| `/hve-core:{n}` | {d} |" for n, d, _ in background]
L += ["", "## Instruction skills (hidden; load by path match or by name)", "", "| Skill | Purpose | Loads when |", "|---|---|---|"]
L += [f"| `{n}` | {d} | `{w}` |" for n, d, _, w in hidden]
L += ["", "## Subagents (dispatched by orchestrators, or `@agent-hve-core:<name>`)", "", "| Agent | Purpose |", "|---|---|"]
L += [f"| `hve-core:{n}` | {d} |" for n, d in agents]
out.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {out}: {len(entry)} entry, {len(background)} background, {len(hidden)} hidden, {len(agents)} agents")
